apiVersion: v1
kind: Secret
metadata:
  name: mcc-liquibase-secret
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  LIQUIBASE_COMMAND_USERNAME: {{ .Values.postgres.username | quote }}
  LIQUIBASE_COMMAND_PASSWORD: {{ .Values.postgres.password | quote }}